deployment/image-index.yml
Added image-index.yml that is needed by Jenkins build job.
=> add image index config

deployment/image-index.yml
=> update image name using prefix tngap

.devcontainer/devcontainer.json, .github/workflows/tests.yaml, Makefile, deployment/docker-compose.override.devcontainer.yml, deployment/docker-compose.override.template.yml, deployment/docker-compose.yml
Merging worker and beat
The updated SDD : https://github.com/kartoza/kartoza-devops/pull/1745
=> Merge worker and beat

.github/workflows/mkdocs.yml
=> Add mkdocs file to github workflow

docs/mkdocs-base.yml, docs/mkdocs-html.yml
=> Fix the buid

django_project/gap/models/crop_insight.py, django_project/spw/tests/test_crop_insight_generator.py
This will fix https://github.com/kartoza/tomorrownow_gap/pull/103
The example returns
=> Update header of csv

django_project/spw/generator/crop_insight.py, django_project/spw/tests/test_crop_insight_generator.py
This will fix https://github.com/kartoza/tomorrownow_gap/issues/93
=> Add retry method on generate spw

django_project/gap/apps.py, django_project/gap/ingestor/salient.py, django_project/gap/tests/utils/test_salient.py, django_project/gap/utils/salient.py
=> monkey patch salient download query to use stream and chunks

django_project/gap_api/api_views/crop_insight.py, django_project/gap_api/api_views/measurement.py
@mvmaltitz, I need your  help to review below text for API endpoint description.
=> Change api endpoint description

deployment/docker/requirements.txt, django_project/core/admin.py, django_project/core/forms.py, django_project/core/settings/contrib.py, django_project/core/tests/test_form.py, django_project/gap_api/tests/test_user_api.py
This will fix https://github.com/kartoza/tomorrownow_gap/issues/53
=> Add django token using knox

docs/src/developer/architecture.md
This PR is for the `Table of contents` not showing on the architecture page issue.
=> Fix table of content issue in architecture file

django_project/gap/models/crop_insight.py, django_project/spw/tests/test_crop_insight_generator.py
This will fix https://github.com/kartoza/tomorrownow_gap/issues/166
=> Add date to the crop filename

django_project/gap/providers/tio.py, django_project/spw/generator/main.py
This is for #168.
Sample input data for R code that is generated on Oct 4th:
[596ed36b-cb03-4d60-8869-00d436c0adaf.csv](https://github.com/user-attachments/files/17254165/596ed36b-cb03-4d60-8869-00d436c0adaf.csv)
It has:
- 37 days of historical data
- Today's forecast
- next 13 days forecast
Total is 51 data.
=> Fix fetching historical data from D-37

django_project/gap/ingestor/tio_shortterm.py, django_project/gap/providers/tio.py, django_project/gap/tests/ingestor/test_arable.py, django_project/gap/tests/ingestor/test_tahmo_api.py, django_project/gap/tests/ingestor/test_tio_shortterm_collector.py, django_project/gap/tests/ingestor/test_wind_borne_sistems.py, django_project/gap/tests/mock_response.py, django_project/gap/tests/providers/test_tio.py
The collector will pull timelines data from Tio:
- historical data from D-6 to D-1
- Today's forecast
- 14 days forecast
Total data: 21 days.
=> Change date range Tio Short-term Forecast Collector

docs/src/developer/api/guide/measurment.md
This PR is for the issue #191 
Took some extra time due to the data
=> Updated gap input table and attribute table

docs/src/developer/api/guide/index.md, docs/src/developer/api/guide/measurement.md
=> update product type description in API doc

deployment/docker/requirements.txt, django_project/core/urls.py, django_project/core/views/__init__.py, django_project/core/views/flower.py, django_project/core/views/preferences.py, django_project/entrypoint.sh, django_project/flower.sh
This is to add flower as celery monitoring tools. Useful to monitor the long running tasks like collector/ingestor.
=> Add flower for celery monitoring tools

docs/src/developer/api/guide/measurement.md
=> Added more descriptive doc

django_project/gap/models/dataset.py, django_project/gap/providers/observation.py, django_project/gap/tests/test_models.py, django_project/gap/utils/reader.py, django_project/gap_api/api_views/measurement.py
=> fix netcdf with quater hourly index

django_project/gap_api/api_views/measurement.py
=> add start_time and end_time attributes

deployment/docker/requirements.txt, django_project/core/settings/contrib.py, django_project/gap/admin/crop_insight.py, django_project/gap/admin/main.py
=> add pagination tabular inlines

django_project/frontend/src/App.tsx, django_project/frontend/src/Home.tsx, django_project/frontend/src/contexts/GapContext.tsx, django_project/frontend/src/styles/App.scss, django_project/frontend/templates/base.html, django_project/frontend/tests/test_views.py, django_project/frontend/views.py
Add links to documentation in the Homepage.
=> Fix homepage

deployment/docker-compose.yml
To use the same version with deployment in Kartoza env.
=> Update postgis version to 16-3.4

docs/src/developer/api/guide/access-api-using-jupyter.md, docs/src/developer/api/guide/access-api-using-r.md, docs/src/developer/api/guide/index.md, examples/sample.R, examples/sample.ipynb, examples/sample.py
=> Add code example for api

django_project/gap/providers/tio.py, django_project/gap/tests/providers/test_tio_zarr.py, django_project/gap/utils/reader.py
=> read past forecast date for tio shortterm

django_project/gap/providers/observation.py, django_project/gap/tests/utils/test_netcdf.py, django_project/gap/utils/dask.py, django_project/gap/utils/reader.py
=> Improve dask to csv

django_project/gap/ingestor/cbam_bias_adjust.py, django_project/gap/ingestor/tio_shortterm.py
=> replace np.empty with np full nan

deployment/docker-compose.override.devcontainer.yml, deployment/docker/requirements.txt, django_project/dcas/functions.py, django_project/dcas/management/commands/check_output.py, django_project/dcas/management/commands/run_dcas_pipeline.py, django_project/dcas/outputs.py, django_project/dcas/partitions.py, django_project/dcas/pipeline.py, django_project/dcas/queries.py, django_project/dcas/rules/rule_engine.py, django_project/dcas/utils.py
This PR includes data pipeline process:
- Data Collection (random generation for each attribute)
- Preprocess raw grid data for daily gdd, temperature, humidity, etc.
- Merge raw grid data with crop and planting_date data
- Process total GDD, precipitations, growth stage, and message codes
- Store the Grid data to parquet files
The data pipeline is using dask.dataframe to achieve scallability and better memory management when handing large dataset.
TODO:
Once this PR is merged, the next tickets to work on are:
- #335 
- #329 
- Merge grid data with FarmRegistry to produce final csv output
=> Feat dcas process

docs/src/developer/api/guide/access-api-using-r.md, examples/sample.R, examples/sample_points.R
=> add sample to fetch API by points in CSV

django_project/gap/fixtures/14.crop.json
This is to allign with FarmRegistry data and DCAS rule csv.
cc: @osundwajeff
=> Fix crop names

django_project/dcas/management/commands/check_output.py, django_project/dcas/partitions.py, django_project/dcas/pipeline.py, django_project/dcas/queries.py, django_project/dcas/tests/base.py, django_project/dcas/tests/test_partitions.py, django_project/dcas/tests/test_pipeline.py, django_project/gap/factories/crop_insight.py, django_project/gap/factories/farm.py
This is for #362: Merge gdd base and cap temperature from GDDConfig
=> Merge GDD base and cap temperatures

docs/src/developer/api/guide/measurement.md
Updated the dataset this PR is for issue #348
=> Update tahmo attribute docs

deployment/docker/requirements.txt, django_project/core/settings/contrib.py, django_project/core/settings/project.py, django_project/gap_api/admin.py, django_project/gap_api/models/api_request_log.py, django_project/gap_api/resources.py, django_project/gap_api/tests/test_api_request_resources.py
#338 
Used: https://github.com/auto-mat/django-import-export-celery
https://github.com/user-attachments/assets/1c6b6f6b-099a-4d2d-afc8-f327e358033c
=> Add export api request logs

django_project/dcas/functions.py, django_project/dcas/partitions.py, django_project/dcas/pipeline.py, django_project/dcas/service.py, django_project/dcas/tests/test_get_growth_service.py, django_project/dcas/tests/test_pipeline_functions.py
=> identify growth stage and its start_date

django_project/gap/ingestor/farm_registry.py, django_project/gap/tests/ingestor/test_farm_registry.py
Fix #364 
Fix farm registry ingestor data handling and update test
=> Fix farm registry ingestor

django_project/dcas/functions.py, django_project/dcas/inputs.py, django_project/dcas/tests/test_pipeline_functions.py, django_project/dcas/tests/test_pipeline_inputs.py
=> Fix data collection for grid

django_project/dcas/management/commands/run_dcas_pipeline.py, django_project/dcas/outputs.py, django_project/dcas/partitions.py, django_project/dcas/pipeline.py, django_project/dcas/queries.py, django_project/dcas/tests/test_partitions.py, django_project/dcas/tests/test_pipeline.py, django_project/dcas/tests/test_pipeline_outputs.py, django_project/dcas/tests/test_pipeline_queries.py, django_project/dcas/utils.py
- Add merge FarmRegistry with Grid Data
- Extract to csv
- Fix #379
=> Feat pipeline output csv

django_project/dcas/functions.py, django_project/dcas/pipeline.py, django_project/dcas/service.py, django_project/dcas/tests/test_get_growth_service.py, django_project/dcas/tests/test_pipeline_functions.py
=> Add load and cleanup matrix functions

django_project/dcas/pipeline.py, django_project/dcas/queries.py, django_project/dcas/tests/base.py, django_project/dcas/tests/test_pipeline.py, django_project/dcas/tests/test_pipeline_queries.py, django_project/dcas/tests/test_rule_engine.py
=> use today -1 for calculating total gdd

django_project/dcas/functions.py, django_project/dcas/service.py, django_project/dcas/tests/test_get_growth_service.py, django_project/dcas/tests/test_pipeline_functions.py
=> Feat fix growth stage calc

django_project/dcas/outputs.py, django_project/dcas/partitions.py, django_project/dcas/pipeline.py, django_project/dcas/tests/test_utils.py, django_project/dcas/utils.py
=> set config for duckdb number of threads

django_project/gap/ingestor/tio_shortterm.py, django_project/gap/tests/ingestor/test_tio_shortterm_collector.py
=> change payload to tio API using centroid

django_project/core/tests/test_date.py, django_project/core/utils/date.py, django_project/gap/admin/main.py, django_project/gap/ingestor/arable.py, django_project/gap/ingestor/base.py, django_project/gap/ingestor/cbam.py, django_project/gap/ingestor/tahmo.py, django_project/gap/ingestor/tahmo_api.py, django_project/gap/ingestor/wind_borne_systems.py, django_project/gap/models/dataset.py, django_project/gap/models/ingestor.py, django_project/gap/tasks/collector.py, django_project/gap/tasks/ingestor.py, django_project/gap/tests/ingestor/test_arable.py, django_project/gap/tests/ingestor/test_cbam.py, django_project/gap/tests/ingestor/test_salient.py, django_project/gap/tests/ingestor/test_tahmo_api.py, django_project/gap/tests/ingestor/test_tio_shortterm_ingestor.py, django_project/gap/tests/ingestor/test_wind_borne_sistems.py, django_project/gap/tests/test_models.py, django_project/gap/tests/utils/test_parquet.py, django_project/gap/utils/parquet.py
=> Feat update ingestor parquet

django_project/gap/providers/tio.py
=> update query to use timelines D-1 for past dates

django_project/dcas/inputs.py
=> change precipitation to use total_rainfall

django_project/dcas/partitions.py
Fix one of issue found in #437
=> use planting date + 1 for start of gdd cumulative sum

django_project/core/settings/project.py
=> add swagger settings for login and logout URLs

django_project/core/tests/test_background_task.py, django_project/gap/tasks/collector.py, django_project/gap/tasks/ingestor.py, django_project/gap/tests/tasks/test_collector.py, django_project/gap/tests/tasks/test_ingestor.py
=> fix trigger notify ingestor failed

django_project/gap/tasks/collector.py, django_project/gap/tests/ingestor/test_salient.py
Fix https://kartoza-pty-ltd.sentry.io/issues/31685215/?alert_rule_id=48384&alert_timestamp=1740974409178&alert_type=email&notification_uuid=bc7da06d-67de-4f46-a663-3548ef809b01&project=4507745823424592&referrer=digest_email
=> fix unbound session variable

django_project/dcas/partitions.py, django_project/dcas/tests/test_partitions.py
=> calculate seasonal precip only after planting date

deployment/docker/requirements.txt, django_project/gap/ingestor/salient.py
=> Fix salient ingestor

django_project/gap/fixtures/4.dataset_type.json, django_project/gap/fixtures/6.unit.json, django_project/gap/fixtures/7.attribute.json, django_project/gap/fixtures/8.dataset_attribute.json, django_project/gap/ingestor/salient.py
Adding missing attributes for #392
=> Feat cbam 2.1 attribs

django_project/gap/fixtures/4.dataset_type.json, django_project/gap/fixtures/5.dataset.json, django_project/gap/providers/tio.py, django_project/gap_api/api_views/measurement.py, django_project/gap_api/templates/gap/swagger-ui.html
Fix https://github.com/kartoza/tomorrownow_gap/issues/489 and issue on swagger
=> fix tomorrow io historical type

django_project/gap/models/crop_insight.py, django_project/gap/tests/crop_insight/test_task_crop_insight.py, django_project/plumber_initialize.py, django_project/spw/generator/crop_insight.py, django_project/spw/generator/main.py, django_project/spw/tasks.py, django_project/spw/utils/plumber.py
- Fix pulling historical data 38 days
- Use multithreaded when executing plumber
=> Parallel plumber

django_project/gap/ingestor/salient.py, django_project/gap/providers/salient.py, django_project/gap/tests/ingestor/test_salient.py
Fix https://github.com/kartoza/tomorrownow_gap/issues/442
=> Feat salient 8months

django_project/gap/ingestor/farm_registry.py
This is to fix temporary table generating wal files and consuming lot of spaces in Staging
=> use unlogged temporary table

django_project/gap/ingestor/base.py, django_project/gap/ingestor/cbam_bias_adjust.py, django_project/gap/ingestor/farm_registry.py, django_project/gap/ingestor/salient.py, django_project/gap/ingestor/tio_shortterm.py, django_project/gap/tests/ingestor/test_salient.py
Fix https://github.com/kartoza/tomorrownow_gap/issues/517
=> salient use update region

django_project/gap/admin/crop_insight.py, django_project/prise/admin.py
This is to fix admin page causing 502 Bad Gateway due to loading all farms as filters or dropdown fields.
=> remove farm as editable field and filter

django_project/gap/ingestor/farm_registry.py, django_project/gap/tests/ingestor/test_farm_registry.py
=> Update farm registry ingestor

django_project/core/celery.py, django_project/dcas/admin.py, django_project/dcas/apps.py, django_project/dcas/models/output.py, django_project/dcas/tasks.py, django_project/dcas/tests/test_tasks.py, django_project/dcas/tests/test_utils.py, django_project/dcas/utils.py
=> add task to clean up old dcas output file

django_project/core/apps.py, django_project/core/celery.py, django_project/core/tasks.py, django_project/core/tests/test_tasks.py, django_project/core/utils/emails.py, django_project/dcas/tasks.py, django_project/gap/tasks/collector.py, django_project/gap/tasks/crop_insight.py, django_project/gap/tasks/ingestor.py
=> add notify alert when spw/dcas failed

django_project/dcas/outputs.py, django_project/dcas/tasks.py
=> fix issue on extract csv queries

django_project/gap/ingestor/tio_shortterm.py, django_project/gap/tests/ingestor/test_tio_shortterm_collector.py
=> use transaction for batch insert

django_project/gap/ingestor/salient.py, django_project/gap/ingestor/tio_shortterm.py, django_project/gap/tasks/collector.py, django_project/gap/tests/ingestor/test_tio_shortterm_ingestor.py
=> fix tio ingestor

django_project/gap/ingestor/tio_shortterm.py
Fix https://github.com/kartoza/tomorrownow_gap/issues/575.
=> use raw results to avoid converting to json

django_project/core/admin.py, django_project/core/models/table_usage.py, django_project/core/tests/test_table_usage.py, django_project/dcas/admin.py, django_project/dcas/tasks.py, django_project/dcas/tests/test_tasks.py, django_project/spw/tests/test_crop_insight_generator.py
=> Feat reclaim db space

django_project/dcas/tests/test_pipeline_inputs.py, django_project/gap/providers/observation.py, django_project/gap/providers/tio.py, django_project/gap/tests/providers/test_tio_zarr.py, django_project/gap/utils/reader.py, django_project/spw/tests/test_generator.py
=> Feat tio hourly reader

django_project/gap/providers/__init__.py, django_project/gap/providers/airborne_observation.py, django_project/gap/providers/base.py, django_project/gap/providers/cbam.py, django_project/gap/providers/observation.py, django_project/gap/providers/salient.py, django_project/gap/providers/tio.py, django_project/gap/tests/providers/test_salient.py, django_project/gap/tests/utils/test_netcdf.py, django_project/gap/utils/netcdf.py, django_project/gap/utils/reader.py, django_project/gap/utils/zarr.py, django_project/gap_api/api_views/measurement.py, django_project/gap_api/templates/gap/swagger-ui.html, django_project/gap_api/tests/test_measurement_api.py, django_project/gap_api/tests/test_user_file.py
=> add forecast date salient to api; refactor provider builder

django_project/gap/fixtures/2.provider.json, django_project/gap/fixtures/4.dataset_type.json, django_project/gap/fixtures/5.dataset.json, django_project/gap/fixtures/8.dataset_attribute.json, django_project/gap/providers/__init__.py, django_project/gap/providers/cbam.py, django_project/gap/providers/tamsat.py, django_project/gap/providers/tio.py, django_project/gap/tests/providers/test_cbam.py, django_project/gap/tests/providers/test_tamsat.py, django_project/gap/tests/providers/test_tio_zarr.py, django_project/gap/utils/netcdf.py, django_project/gap/utils/reader.py, django_project/gap_api/api_views/measurement.py
=> Feat ltn data

django_project/gap/fixtures/4.dataset_type.json, django_project/gap/fixtures/7.attribute.json, django_project/gap/fixtures/8.dataset_attribute.json, django_project/gap/ingestor/tomorrowio/collector.py, django_project/gap/ingestor/tomorrowio/duckdb_ingestor.py, django_project/gap/providers/tio.py, django_project/gap/tests/ingestor/test_tio_shortterm_collector.py, django_project/gap/tests/ingestor/test_tio_shortterm_ingestor.py, django_project/gap/tests/providers/test_tio_zarr.py
=> Feat tio hourly update

django_project/gap/fixtures/4.dataset_type.json, django_project/gap/fixtures/5.dataset.json, django_project/gap/tests/providers/test_tamsat.py, django_project/permission/tests/test_admin.py, django_project/permission/tests/test_permission.py, docs/src/developer/api/guide/measurement.md
=> update fixtures with latest naming

django_project/frontend/src/features/landing/HeroSection.tsx
Fix issue fixed background on ios devices
=> disable fixed background on hero section mobile view

django_project/core/celery.py, django_project/gap/tasks/__init__.py, django_project/gap/tasks/incomplete_signups.py
Fixes #671
Note: I have update the message from `pending` to `incomplete`.
=> Fix: clean up task failure

django_project/frontend/src/features/auth/LoginForm.tsx, django_project/frontend/src/utils/analytics.ts
=> Add analytics event when log in using social auth

django_project/frontend/src/features/auth/LoginForm.tsx
Ensure confirmed password is the same before submitting reset password
Fixes #696
https://github.com/user-attachments/assets/69a93050-8cdb-4576-8cb9-4d19519774fd
=> [BUG] Ensure confirmed password is the same before reset password

django_project/frontend/src/components/Navigation.tsx, django_project/frontend/tests/test_views.py, django_project/frontend/views.py
Fixes #697
Mobile view:
https://github.com/user-attachments/assets/beedc650-f487-4680-a30b-9f47de374dce
Download (only tested on local):
https://github.com/user-attachments/assets/a2ef289a-e5a1-495e-b6cf-b7727c120b99
=> [BUG] DCAS CSV page

django_project/frontend/api_views/auth/__init__.py, django_project/frontend/api_views/auth/login.py, django_project/frontend/api_views/auth/user.py, django_project/frontend/models.py, django_project/frontend/src/App.tsx, django_project/frontend/src/app/router.tsx, django_project/frontend/src/components/Navigation.tsx, django_project/frontend/src/components/ProtectedRoute.tsx, django_project/frontend/src/features/auth/LoginForm.tsx, django_project/frontend/src/features/auth/authSlice.ts, django_project/frontend/src/features/auth/type.ts, django_project/frontend/src/hooks/useAuth.ts, django_project/frontend/src/hooks/useAuthInit.ts, django_project/frontend/src/hooks/useNavigateWithEvent.ts, django_project/frontend/src/hooks/useProtectedRoute.ts, django_project/frontend/src/pages/DcasCsvList.tsx, django_project/frontend/src/pages/ErrorPage.tsx, django_project/frontend/src/types/index.ts, django_project/frontend/tests/auth/test_user_api.py, django_project/frontend/urls.py, django_project/gap_api/tests/test_api_job_status.py
Fix https://github.com/kartoza/tomorrownow_gap/issues/704
=> fix page permission in frontend

django_project/gap/providers/salient.py, django_project/gap/tests/providers/test_salient.py, django_project/gap/utils/netcdf.py, django_project/gap/utils/reader.py
Fix https://github.com/kartoza/tomorrownow_gap/issues/736
=> fix salient convert to json with ensembles

django_project/frontend/src/Swagger.tsx, django_project/frontend/src/app/swaggerRouter.tsx, django_project/frontend/src/components/ProfileDropdown.tsx, django_project/frontend/src/components/SimpleNavBar.tsx, django_project/frontend/src/features/auth/LoginForm.tsx, django_project/frontend/src/hooks/useNavigateWithEvent.ts, django_project/frontend/webpack.config.js, django_project/gap_api/api_views/measurement.py, django_project/gap_api/templates/gap/swagger-ui.html, django_project/gap_api/utils/helper.py
=> replace swagger topbar with navigation component

django_project/core/celery.py, django_project/gap/migrations/0070_cropinsightrequest_method_preferences_tamsat_url.py, django_project/gap/models/crop_insight.py, django_project/spw/admin.py, django_project/spw/apps.py, django_project/spw/migrations/0005_spwexecutionlog.py, django_project/spw/models.py, django_project/spw/tamsat/base.py, django_project/spw/tamsat/generator.py, django_project/spw/tamsat/planting_date_api.py, django_project/spw/tamsat/reader.py, django_project/spw/tasks.py, django_project/spw/tests/test_tamsat.py
=> Feat run tamsat task

django_project/gap/models/crop_insight.py, django_project/gap/models/farm_group.py, django_project/spw/tamsat/reader.py
Fix #764.
Preview:
[SPW_Regen_organics_pilot_2025_07_31_3d259451_d6a4_47f6_842a_d8e23cc9d_OmVvLQf.csv](https://github.com/user-attachments/files/21528184/SPW_Regen_organics_pilot_2025_07_31_3d259451_d6a4_47f6_842a_d8e23cc9d_OmVvLQf.csv)
=> Add tamsat spw to csv output

django_project/gap/admin/crop_insight.py, django_project/gap/tasks/cleanup.py, django_project/gap/tests/tasks/test_cleanup.py
Remove old unused the farm forecast data
=> Feat remove table forecast data

django_project/dcas/outputs.py
Try reducing memory consumptions of geometry conversion before writing DCAS partitions to geoparquet.
=> fix geom conversion

django_project/core/management/commands/load_fixtures.py
Sort load fixtures based on the numbering, also fix #776
=> fix load fixtures

django_project/gap/ingestor/farm.py
=> fix update geom in farm ingestor

django_project/gap/ingestor/google/gee.py
=> check size of filtered image collection

django_project/spw/generator/crop_insight.py
Fix issue in https://kartoza-pty-ltd.sentry.io/issues/64104410/?project=4507745823424592&referrer=project-issue-stream
=> skip insert if forecast value is None
